version: '3.8'
services:
  back:
    environment:
      - NODE_ENV=development
    container_name: back
    build:
      context: ./back
      dockerfile: Dockerfile
    ports: ['8080:8080']
    depends_on: ['db']
    command: 'npm run start-dev'
    volumes:
      - './back:/back'
      - './back/node_modules'
  db:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=ipfs-proxy
    container_name: db
    image: mongo
    ports: ['27017:27017']
    volumes:
      - ./back/.db:/data/db
  front:
    container_name: front
    stdin_open: true
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - './front:/front'
      - './front/node_modules'
    command: 'npm start'
    
  ipfs:
    container_name: ipfs
    image: ipfs/go-ipfs
    environment:
      - IPFS_PROFILE=server
  
  
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: proxy
    depends_on:
      - db
      - ipfs
    ports:
      - "5000:5000"

networks:
  default: